/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as ConsoleRouteImport } from './routes/_console'
import { Route as ConsoleAnalysisRouteImport } from './routes/_console/analysis'
import { Route as ConsoleOverviewRouteImport } from './routes/_console/overview'
import { Route as ConsoleProjectsRouteImport } from './routes/_console/projects'
import { Route as ConsoleSettingsRouteImport } from './routes/_console/settings'
import { Route as ConsoleDeploymentsIndexRouteImport } from './routes/_console/deployments/index'
import { Route as ConsoleDeploymentsJobIdRouteImport } from './routes/_console/deployments/$jobId'
import { Route as ConsoleReportsIndexRouteImport } from './routes/_console/reports/index'
import { Route as ConsoleReportsJobIdRouteImport } from './routes/_console/reports/$jobId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/_console',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleAnalysisRoute = ConsoleAnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleOverviewRoute = ConsoleOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleProjectsRoute = ConsoleProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleSettingsRoute = ConsoleSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleDeploymentsIndexRoute = ConsoleDeploymentsIndexRouteImport.update({
  id: '/deployments/',
  path: '/deployments/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleDeploymentsJobIdRoute = ConsoleDeploymentsJobIdRouteImport.update({
  id: '/deployments/$jobId',
  path: '/deployments/$jobId',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleReportsIndexRoute = ConsoleReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleReportsJobIdRoute = ConsoleReportsJobIdRouteImport.update({
  id: '/reports/$jobId',
  path: '/reports/$jobId',
  getParentRoute: () => ConsoleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/analysis': typeof ConsoleAnalysisRoute
  '/overview': typeof ConsoleOverviewRoute
  '/projects': typeof ConsoleProjectsRoute
  '/settings': typeof ConsoleSettingsRoute
  '/deployments/$jobId': typeof ConsoleDeploymentsJobIdRoute
  '/reports/$jobId': typeof ConsoleReportsJobIdRoute
  '/deployments/': typeof ConsoleDeploymentsIndexRoute
  '/reports/': typeof ConsoleReportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/analysis': typeof ConsoleAnalysisRoute
  '/overview': typeof ConsoleOverviewRoute
  '/projects': typeof ConsoleProjectsRoute
  '/settings': typeof ConsoleSettingsRoute
  '/deployments/$jobId': typeof ConsoleDeploymentsJobIdRoute
  '/reports/$jobId': typeof ConsoleReportsJobIdRoute
  '/deployments': typeof ConsoleDeploymentsIndexRoute
  '/reports': typeof ConsoleReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/_console': typeof ConsoleRouteWithChildren
  '/_console/analysis': typeof ConsoleAnalysisRoute
  '/_console/overview': typeof ConsoleOverviewRoute
  '/_console/projects': typeof ConsoleProjectsRoute
  '/_console/settings': typeof ConsoleSettingsRoute
  '/_console/deployments/$jobId': typeof ConsoleDeploymentsJobIdRoute
  '/_console/reports/$jobId': typeof ConsoleReportsJobIdRoute
  '/_console/deployments/': typeof ConsoleDeploymentsIndexRoute
  '/_console/reports/': typeof ConsoleReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/analysis'
    | '/overview'
    | '/projects'
    | '/settings'
    | '/deployments/$jobId'
    | '/reports/$jobId'
    | '/deployments/'
    | '/reports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/analysis'
    | '/overview'
    | '/projects'
    | '/settings'
    | '/deployments/$jobId'
    | '/reports/$jobId'
    | '/deployments'
    | '/reports'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/_console'
    | '/_console/analysis'
    | '/_console/overview'
    | '/_console/projects'
    | '/_console/settings'
    | '/_console/deployments/$jobId'
    | '/_console/reports/$jobId'
    | '/_console/deployments/'
    | '/_console/reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ConsoleRoute: typeof ConsoleRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_console': {
      id: '/_console'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_console/analysis': {
      id: '/_console/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof ConsoleAnalysisRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/overview': {
      id: '/_console/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof ConsoleOverviewRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/projects': {
      id: '/_console/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ConsoleProjectsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/settings': {
      id: '/_console/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ConsoleSettingsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/deployments/': {
      id: '/_console/deployments/'
      path: '/deployments'
      fullPath: '/deployments/'
      preLoaderRoute: typeof ConsoleDeploymentsIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/deployments/$jobId': {
      id: '/_console/deployments/$jobId'
      path: '/deployments/$jobId'
      fullPath: '/deployments/$jobId'
      preLoaderRoute: typeof ConsoleDeploymentsJobIdRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/reports/': {
      id: '/_console/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ConsoleReportsIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/reports/$jobId': {
      id: '/_console/reports/$jobId'
      path: '/reports/$jobId'
      fullPath: '/reports/$jobId'
      preLoaderRoute: typeof ConsoleReportsJobIdRouteImport
      parentRoute: typeof ConsoleRoute
    }
  }
}

interface ConsoleRouteChildren {
  ConsoleAnalysisRoute: typeof ConsoleAnalysisRoute
  ConsoleOverviewRoute: typeof ConsoleOverviewRoute
  ConsoleProjectsRoute: typeof ConsoleProjectsRoute
  ConsoleSettingsRoute: typeof ConsoleSettingsRoute
  ConsoleDeploymentsJobIdRoute: typeof ConsoleDeploymentsJobIdRoute
  ConsoleReportsJobIdRoute: typeof ConsoleReportsJobIdRoute
  ConsoleDeploymentsIndexRoute: typeof ConsoleDeploymentsIndexRoute
  ConsoleReportsIndexRoute: typeof ConsoleReportsIndexRoute
}

const ConsoleRouteChildren: ConsoleRouteChildren = {
  ConsoleAnalysisRoute: ConsoleAnalysisRoute,
  ConsoleOverviewRoute: ConsoleOverviewRoute,
  ConsoleProjectsRoute: ConsoleProjectsRoute,
  ConsoleSettingsRoute: ConsoleSettingsRoute,
  ConsoleDeploymentsJobIdRoute: ConsoleDeploymentsJobIdRoute,
  ConsoleReportsJobIdRoute: ConsoleReportsJobIdRoute,
  ConsoleDeploymentsIndexRoute: ConsoleDeploymentsIndexRoute,
  ConsoleReportsIndexRoute: ConsoleReportsIndexRoute,
}

const ConsoleRouteWithChildren =
  ConsoleRoute._addFileChildren(ConsoleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ConsoleRoute: ConsoleRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
